# Semgrep configuration for Phase 5
# Pattern-based code scanning configuration

rules:
  - id: hardcoded-secret
    patterns:
      - pattern-either:
          - pattern: password = "..."
          - pattern: api_key = "..."
          - pattern: secret = "..."
          - pattern: token = "..."
    message: Possible hardcoded secret detected
    languages: [python]
    severity: ERROR

  - id: sql-injection
    patterns:
      - pattern-either:
          - pattern: |
              execute($SQL)
          - pattern: |
              query_raw($SQL)
    message: Possible SQL injection vulnerability
    languages: [python]
    severity: WARNING

  - id: unsafe-yaml-load
    pattern: yaml.load(...)
    message: Use yaml.safe_load() instead of yaml.load()
    languages: [python]
    severity: WARNING

  - id: unsafe-pickle
    pattern: pickle.loads(...)
    message: Unsafe deserialization with pickle
    languages: [python]
    severity: ERROR

  - id: weak-crypto
    patterns:
      - pattern-either:
          - pattern: hashlib.md5(...)
          - pattern: hashlib.sha1(...)
    message: Weak cryptographic hash function
    languages: [python]
    severity: WARNING
